### ISSUE TITLE
Windows本地工作时识别模块出错

### ISSUE THREAD

**Issue by zl70971** [lovegaoshi/ipynb#4]
2023-05-22 19:48:02.112 | WARNING  | __main__:recognize_song:234 - 识别失败。
2023-05-22 19:48:02.115 | INFO     | __main__:shazam:186 - 开始识别 E:\tmp\1_0.mp4 。
2023-05-22 19:48:02.124 | ERROR    | __main__:recognize_song:226 - An error has been caught in function 'recognize_song', process 'MainProcess' (11700), thread 'MainThread' (15292):
Traceback (most recent call last):

  File "D:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
           │         └ <code object <module> at 0x00000245477D1F20, file "D:\Python310\lib\site-packages\ipykernel_launcher.py", line 1>
           └ <function _run_code at 0x00000245477E0CA0>

  File "D:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': 'Entry point for launching an IPython kernel.\n\nThis is separate from the ipykernel pack...
         └ <code object <module> at 0x00000245477D1F20, file "D:\Python310\lib\site-packages\ipykernel_launcher.py", line 1>

  File "D:\Python310\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from 'D:\\Python310\\lib\\site-packages\\ipykernel\\kernelapp.py'>

  File "D:\Python310\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x000002454BE36A70>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x00000245474C48E0>

  File "D:\Python310\lib\site-packages\ipykernel\kernelapp.py", line 725, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x000002454BE37640>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x000002454BE5E5C0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x00000245474C48E0>

  File "D:\Python310\lib\site-packages\tornado\platform\asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x00000245495C1240>
    │    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x000002454BE5E5C0>

  File "D:\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000245495C2D40>
    └ <_WindowsSelectorEventLoop running=True closed=False debug=False>

  File "D:\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000024549566710>
    └ <Handle Task.task_wakeup(<Future finis...430>, ...],))>)>

  File "D:\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...430>, ...],))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...430>, ...],))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...430>, ...],))>)>

  File "D:\Python310\lib\site-packages\ipykernel\kernelbase.py", line 513, in dispatch_queue
    await self.process_one()
          │    └ <function Kernel.process_one at 0x000002454B5C6EF0>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x000002454BE5EB90>

  File "D:\Python310\lib\site-packages\ipykernel\kernelbase.py", line 502, in process_one
    await dispatch(*args)
          │         └ ([<zmq.sugar.frame.Frame object at 0x000002454BEE7690>, <zmq.sugar.frame.Frame object at 0x000002454BEE6770>, <zmq.sugar.fram...
          └ <bound method Kernel.dispatch_shell of <ipykernel.ipkernel.IPythonKernel object at 0x000002454BE5EB90>>

  File "D:\Python310\lib\site-packages\ipykernel\kernelbase.py", line 409, in dispatch_shell
    await result
          └ <coroutine object Kernel.execute_request at 0x000002454BDF3ED0>

  File "D:\Python310\lib\site-packages\ipykernel\kernelbase.py", line 729, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x000002452766EC70>

  File "D:\Python310\lib\site-packages\ipykernel\ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x000002454BE34310>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000002454BE5F070>

  File "D:\Python310\lib\site-packages\ipykernel\zmqshell.py", line 540, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': None}
                             └ ("# 切割，将这里的文件名修改为自己下载的文件名字。名字里不要有中文、标点等。\nraw_file_path = r'E:\\AI\\1\\1.mp4'\nseg_out_dir = r'E:\\tmp'\nrecognized_dir = r'E...

  File "D:\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3009, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x000002454A5131C0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000002454BE5F070>

  File "D:\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3064, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x000002452766EC00>
             └ <function _pseudo_sync_runner at 0x000002454A386B00>

  File "D:\Python310\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x000002452766EC00>

  File "D:\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3269, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ 'C:\\Users\\panorama\\AppData\\Local\\Temp\\ipykernel_11700\\2329454151.py'
                       │    │             │        └ [<ast.Assign object at 0x000002454BECED10>, <ast.Assign object at 0x000002454BECDBD0>, <ast.Assign object at 0x000002454BF78F...
                       │    │             └ <ast.Module object at 0x000002454BECD600>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x000002454A513490>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000002454BE5F070>

  File "D:\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3448, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 2454bf79c00, execution_count=2 error_before_exec=None error_in_exec=None info=<ExecutionInfo objec...
             │    │        └ <code object <module> at 0x0000024574E4D210, file "C:\Users\panorama\AppData\Local\Temp\ipykernel_11700\2329454151.py", line 1>
             │    └ <function InteractiveShell.run_code at 0x000002454A513520>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000002454BE5F070>

  File "D:\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ {'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, ...
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000002454BE5F070>
         │         │    └ <property object at 0x000002454A38EE80>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000002454BE5F070>
         └ <code object <module> at 0x0000024574E4D210, file "C:\Users\panorama\AppData\Local\Temp\ipykernel_11700\2329454151.py", line 1>

  File "C:\Users\panorama\AppData\Local\Temp\ipykernel_11700\2329454151.py", line 9, in <module>
    recognize_song(this_seg_out_dir, recognized_dir)
    │              │                 └ 'E:\\tmp'
    │              └ 'E:\\tmp'
    └ <function recognize_song at 0x00000245276BD6C0>

> File "C:\Users\panorama\AppData\Local\Temp\ipykernel_11700\2769385435.py", line 226, in recognize_song
    recognize_result = shazam(file_path)
                       │      └ 'E:\\tmp\\1_0.mp4'
                       └ <function shazam at 0x00000245276BCCA0>

  File "C:\Users\panorama\AppData\Local\Temp\ipykernel_11700\2769385435.py", line 187, in shazam
    recognize_generator = ShazamAPI.Shazam(
                          │         └ <class 'ShazamAPI.api.Shazam'>
                          └ <module 'ShazamAPI' from 'D:\\Python310\\lib\\site-packages\\ShazamAPI\\__init__.py'>

TypeError: Shazam.__init__() got an unexpected keyword argument 'lang'
2023-05-22 19:48:02.133 | WARNING  | __main__:recognize_song:234 - 识别失败。

**Comment by lovegaoshi** [comment]
shazamAPI 0.0.2 (https://pypi.org/project/ShazamAPI/)  跟 github上 (https://github.com/Numenorean/ShazamAPI/blob/main/ShazamAPI/api.py) 并不一样 ，帮忙重写代码格式的朋友妹测
你得
`pip install git+https://github.com/Numenorean/ShazamAPI.git`
或者删
`ShazamAPI.Shazam(
        open(mp3, 'rb').read(),
        lang='cn',
        time_zone='Asia/Shanghai'
    )`
中的lang=,time_zone=部分

**Comment by zl70971** [comment]
感谢，已解决
